version: "3"
agent:
  authtoken: 3EG2KA4IMY25jTsLWI1Bx5Gt0Au_tBGjQFubmhsASYCTc7hW  # 💡 如果這裡原本有你的 Token，請保留它
tunnels:
  fruit_shop:
    proto: http
    addr: 8501
    domain: uncrown-pacific-sprout.ngrok-free.dev